apiVersion: apps/v1
kind: Deployment
metadata:
  name: anime-app-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: anime-app
  template:
    metadata:
      labels:
        app: anime-app
    spec:
      containers:
      - name: anime-app-container
        image: houssembel/anime-hub:4
        ports:
        - containerPort: 80
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
---
apiVersion: v1
kind: Service
metadata:
  name: anime-app-service
spec:
  selector:
    app: anime-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
