apiVersion: apps/v1
kind: Deployment
metadata:
  name: anime-app
  labels:
    app: anime-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: anime-app
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: anime-app
    spec:
      containers:
      - name: animehub
        image: houssembel/anime-hub:4
        ports:
        - containerPort: 80
